sudo: required
services:
  - docker
before_install:
  docker build -t miladi7/react-docker -f Dockerfile.dev .
script:
  docker run -e CI=true miladi7/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "react-docker"
  env: "ReactDocker-env"
 
    